export const INIT_PRODUCTS = 'PRODUCTS.INIT';
export const LOADING_PRODUCTS = 'PRODUCTS.LOADING';
export const ADD_TO_CART = 'PRODUCTS.ADDTOCART';
export const REMOVE_FROM_CART = 'PRODUCTS.REMOVEFROMCART';