export const INIT_PRODUCTS = 'PRODUCTS.INIT';
export const LOADING_PRODUCTS = 'PRODUCTS.LOADING';
export const ADD_TO_CART = 'PRODUCTS.ADDTOCART';
export const REMOVE_FROM_CART = 'PRODUCTS.REMOVEFROMCART';
export const BUY_NOW = 'BUY_NOW';
export const LOGIN = "AUTH.LOGIN";
export const LOGOUT = "AUTH.LOGOUT"; 