name: Check code quality

on: pull_request

jobs:
  code_quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Cache
        uses: actions/cache@v2.1.8
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: /
          # An explicit key for restoring and saving the cache
          key: 'test'
          # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
